version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - chrome
    environment:
      PORT: 3100
      BROWSER_WS_ENDPOINT: ws://chrome:3000?token=meu-token-fixo
    volumes:
      - pdfs:/app/pdfs

  chrome:
    image: ghcr.io/browserless/chromium:latest
    ports:
      - "3011:3000"
    environment:
      TOKEN: meu-token-fixo
      CONCURRENT: 10
      TIMEOUT: 300000
    volumes:
      - chrome_data:/data

volumes:
  pdfs:
  chrome_data:
