version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - chrome
    volumes:
      - pdfs:/app/pdfs  # Persiste a pasta pdfs

  chrome:
    image: browserless/chrome:latest
    ports:
      - "3110:3110"
    environment:
      - "MAX_CONCURRENT_SESSIONS=100"
    volumes:
      - chrome_data:/data # Persiste dados do chrome

volumes:
  pdfs:
  chrome_data:
