version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - chrome
    environment:
      PORT: 3100
      BROWSER_WS_ENDPOINT: ws://chrome:3000
    volumes:
      - pdfs:/app/pdfs

  chrome:
    image: browserless/chrome:1.61.0-puppeteer-22.4.1
    environment:
      MAX_CONCURRENT_SESSIONS: 5
      CONNECTION_TIMEOUT: 300000
      PREBOOT_CHROME: "true"
    shm_size: "1gb"

volumes:
  pdfs:
  chrome_data:
